### ISSUE TITLE
Deprecated and misleading help message for containers needs rewording.

### ISSUE THREAD

**Issue by gir489** [Bradenm1/Skyrim-mods#4]
https://i.imgur.com/bYS23Bs.jpg

'Instantly' is a stretch, considering it relies heavily on the Papyrus event system, which can range from 10 milliseconds delay, to 2 second delay, and anywhere in between. There are also spelling mistakes and verbose vague wording. 'fefill' and 'probably cause issues' insuates to the user you have no idea what you're doing. You mention to add your gamertag, which is not displayed anywhere in the message although I think this is a burden you'd rather not carry forever. 

I feel the message should be rewritten as follows:

> Most containers in this room with notable exceptions will resupply themselves as quickly as the game allows after you take the items. Attempting to place items in these containers will result in the game giving them back to you, to prevent alignment issues with Skyrim's memory.

This is a succinct and proper message. What do you think?

**Comment by Bradenm1** [comment]
The mod has a ton of problems. I cringe quite a lot looking at most things in it. I just never got around to fixing issues such as the one you stated. I think that's fine.

**Comment by gir489** [comment]
The next commit will have this change. I'm working on enabling all map markers. Tracking down every single map marker entity in the map is proving to be quite the challenge for sure.
